### ISSUE TITLE
[feature request] openqa-revtui: only show jobs that need review, i.e. need a ticket reference

### ISSUE THREAD

**Issue by okurz** [os-autoinst/openqa-mon#49]
## Motivation
Similar as in https://progress.opensuse.org/issues/94762 test reviewers can benefit from simple "TODO-lists", i.e. only show test failures that need reviewing work. Would be nice if openqa-revtui (by default) can show only the jobs that need review

## Acceptance criteria
* **AC1:** openqa-revtui can be used to show only jobs that need review, i.e. need a ticket reference

**Comment by grisu48** [comment]
I would consider this one as mostly resolved with the introduction of `HideStatus` in the configuration toml files (e.g. [here](https://github.com/grisu48/openqa-mon/blob/master/_review/opensuse-tumbleweed.toml#L6)). This allows to create configuration files that only displays e.g. failed test runs.

The last missing part is to introduce a `reviewed` state therein, so that also failed test runs with a bsc reference can be hidden.

**Comment by grisu48** [comment]
Closing this ticket, as I believe this has been resolved by https://github.com/grisu48/openqa-mon/pull/59. At least that's how I use it on a daily basis.

**Comment by okurz** [comment]
thank you, looks good
