### ISSUE TITLE
clarify job ranges behaviour 

### ISSUE THREAD

**Issue by ilmanzo** [os-autoinst/openqa-mon#80]
when I issue a command like 

`openqa-mon https://openqa.suse.de/tests/10049400+20`

I expect to get info about jobs 10049400-10049419

I get instead status of jobs

```
10049400 
10049401  
10049507 
10049498  
10049404 
10049405  
10049406  
10049517  
10049408  
10049551 
10049410  
10049411
10049548 
10049413 
10049415 
10049416 
10049417 
10049418 
10049419  
10049560  
```

**Comment by grisu48** [comment]
Hi, the reason why `openqa-mon` fetches the job `10049560` instead of `10049520` is that 10049520 got cloned as 10049560 and that you have probably set `Follow = true` in your `~/.openqa-mon.conf`.

See https://openqa.suse.de/tests/10049420

![image](https://user-images.githubusercontent.com/1527829/204562845-628d0b85-c507-43ad-b10c-c44df3bb0d4e.png)

This is the "follow" feature, where you can restart jobs and openqa-mon will "follow" the job restarts instead of staying with the original job.

**Comment by ilmanzo** [comment]
Totally make sense now! Thanks for the clarification.

**Comment by grisu48** [comment]
You're welcome :slightly_smiling_face:
